export const INGREDIENTS = [
  "apple", "avocado", "bacon", "banana", "basil", "beef", "bell pepper", "broccoli",
  "butter", "cabbage", "carrot", "cauliflower", "celery", "cheese", "chicken",
  "cilantro", "cinnamon", "coconut", "corn", "cucumber", "egg", "eggplant", "eel",
  "garlic", "ginger", "grape", "green bean", "green onion", "honey", "jalapeño",
  "kale", "ketchup", "kimchi", "lemon", "lettuce", "lime", "mayo", "milk", "mushroom",
  "mustard", "noodle", "oat", "olive", "onion", "orange", "paprika", "parsley",
  "pasta", "peach", "peanut", "pear", "peas", "pepper", "pineapple", "pork",
  "potato", "pumpkin", "quinoa", "radish", "rice", "rosemary", "salmon", "salt",
  "sausage", "shrimp", "soy sauce", "spinach", "squash", "steak", "strawberry",
  "sugar", "sweet potato", "tofu", "tomato", "tuna", "turkey", "vinegar", "walnut",
  "watermelon", "wheat", "yam", "yogurt", "zucchini",
  // Additional ingredients
  "mussel", "clam", "oyster", "crab", "catfish", "tilapia", "thai chili", "chicken stock",
  "vegetable stock", "beef stock", "sour cream", "worcestershire sauce", "A1 sauce",
  "bean sprouts", "mango", "thyme", "arugula", "coconut milk", "strawberry jelly", "pesto",
  "miso", "fish sauce", "maple syrup", "hot sauce", "caper", "ranch dressing", "salsa",
  // Moderately expanded list
  "asparagus", "artichoke", "bok choy", "brussels sprouts", "chard", "collard greens", "leek",
  "shallot", "turnip", "parsnip", "rutabaga", "beet", "endive", "fennel", "radicchio",
  "cherry", "blueberry", "raspberry", "blackberry", "plum", "apricot", "fig", "pomegranate",
  "kiwi", "passion fruit", "lychee", "persimmon", "guava", "starfruit", "jackfruit",
  "barley", "bulgur", "couscous", "farro", "millet", "spelt", "teff", "sorghum",
  "chia seeds", "flaxseed", "hemp seeds", "pumpkin seeds", "sunflower seeds",
  "almond", "cashew", "pecan", "macadamia", "hazelnut", "pine nut", "brazil nut",
  "duck", "lamb", "venison", "goose", "quail", "rabbit",
  "anchovy", "sardine", "mackerel", "octopus", "squid", "scallop",
  "brie", "feta", "goat cheese", "gouda", "mozzarella", "parmesan", "ricotta", "cheddar",
  "cream cheese", "evaporated milk", "condensed milk", "ghee", "buttermilk",
  "baking powder", "baking soda", "cornstarch", "gelatin", "yeast", "vanilla extract",
  "curry powder", "cumin", "cardamom", "clove", "nutmeg", "allspice", "bay leaf", "saffron",
  "sesame oil", "canola oil", "peanut oil", "grapeseed oil", "coconut oil", "lard",
  "molasses", "brown sugar", "powdered sugar", "agave syrup", "honeydew", "cantaloupe"
]; 